package org.jikespg.uide.parser;

public interface JikesPGKWLexersym {
    public final static int
      Char_DollarSign = 18,
      Char__ = 27,
      Char_a = 8,
      Char_b = 17,
      Char_c = 13,
      Char_d = 10,
      Char_e = 1,
      Char_f = 15,
      Char_g = 19,
      Char_h = 20,
      Char_i = 6,
      Char_j = 21,
      Char_k = 22,
      Char_l = 7,
      Char_m = 12,
      Char_n = 9,
      Char_o = 4,
      Char_p = 11,
      Char_q = 28,
      Char_r = 3,
      Char_s = 2,
      Char_t = 5,
      Char_u = 16,
      Char_v = 23,
      Char_w = 24,
      Char_x = 25,
      Char_y = 14,
      Char_z = 29,
      Char_EOF = 26;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "e",
                 "s",
                 "r",
                 "o",
                 "t",
                 "i",
                 "l",
                 "a",
                 "n",
                 "d",
                 "p",
                 "m",
                 "c",
                 "y",
                 "f",
                 "u",
                 "b",
                 "DollarSign",
                 "g",
                 "h",
                 "j",
                 "k",
                 "v",
                 "w",
                 "x",
                 "EOF",
                 "_",
                 "q",
                 "z"
             };

    public final static boolean isValidForParser = true;
}
